#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""inventory.py — 세계 모델의 단일 원천 (v1).
여기서 골든 레이어(JSON)·mock DB(SQLite)·질문셋이 전부 파생된다.
드라이런 finding 반영: F-1(차원 코드체계 의무), F-2(AS_OF 규약), F-3(만기 패밀리 F7).
"""

CORPUS_AS_OF = "2026-06-15"
DATA_START, DATA_END = "2023-01-01", "2026-05-31"

# ============================================================
# 코드체계 — layer=False 는 '세계에는 존재하나 레이어 CodeDict 미등재'(의도된 결손)
# ============================================================
def _grd10():
    m = {}
    for i in range(1, 11):
        tag = "최우량" if i == 1 else ("최저" if i == 10 else None)
        m[str(i)] = f"{i}등급" + (f"({tag})" if tag else "")
    return m

CODE_SYSTEMS = {
    "CS_LOAN_APPL_STAT": dict(map={"01": "접수", "02": "심사중", "03": "승인", "04": "거절", "05": "취소"}),
    "CS_LOAN_ACCT_STAT": dict(map={"01": "정상", "02": "연체", "03": "기한이익상실", "04": "상각", "05": "완제"}),
    "CS_CARD_STAT":      dict(map={"A": "정상", "S": "정지", "T": "해지", "L": "분실"}),
    "CS_DEP_ACCT_STAT":  dict(map={"10": "신규", "20": "거래중", "30": "거래중지", "40": "해지"}),
    "CS_LOAN_RPYMT_MTHD": dict(map={"01": "원리금균등", "02": "원금균등", "03": "만기일시"}),
    "CS_CARD_RPYMT_MTHD": dict(map={"1": "일시불", "2": "할부", "3": "리볼빙"}),
    "CS_TAX_EXMP":       dict(map={"Y": "면세", "N": "과세", "P": "부분면세", "X": "해당없음"}),
    "CS_TAX_EXMP_RSN":   dict(map={"01": "국가유공자", "02": "장애인", "03": "기초생활수급", "04": "소상공인특례", "XX": "해당없음"}),
    "CS_CRDT_GRD":       dict(map=_grd10(), note="서열형 — 숫자가 낮을수록 우량"),
    "CS_CUST_GRD":       dict(map={"V": "VIP", "G": "골드", "S": "실버", "N": "일반"}),
    "CS_CARD_GRD":       dict(map={"P": "플래티넘", "G": "골드", "C": "클래식"}),
    "CS_DEP_TXN_TYPE":   dict(map={"D": "입금", "W": "출금"}),
    "CS_REGION":         dict(map={"SE": "서울", "GG": "경기", "BS": "부산", "IC": "인천", "DG": "대구", "ETC": "기타"}),
    "CS_BIZ_TYPE":       dict(map={"01": "요식", "02": "유통", "03": "주유", "04": "의료", "05": "온라인", "06": "여행", "07": "기타"}),
    "CS_CLTRL_TYPE":     dict(map={"01": "아파트", "02": "단독주택", "03": "토지", "04": "예적금담보", "05": "기타"}),
    "CS_BNS":            dict(map={"Y": "동의", "N": "미동의", "X": "해당없음"}),
    "CS_GRD_CHG_RSN":    dict(map={"01": "실적상향", "02": "실적하향", "03": "정기재산정"}),
    "CS_RATE_CHG_RSN":   dict(map={"01": "기준금리변동", "02": "우대금리변경", "03": "연체가산"}),
    "CS_LMT_CHG_RSN":    dict(map={"01": "고객요청", "02": "심사하향", "03": "정기재산정"}),
    "CS_CLS_RSN":        dict(map={"01": "고객요청", "02": "만기해지", "03": "강제해지"}),
    "CS_FRAUD_TYPE":     dict(map={"01": "카드도용", "02": "계좌탈취", "03": "보이스피싱", "04": "기타"}),
    "CS_FRAUD_PROC":     dict(map={"01": "탐지", "02": "조사중", "03": "확정", "04": "오탐"}),
    "CS_LOAN_PRDT_TYPE": dict(map={"01": "신용", "02": "담보", "03": "전세", "04": "정책"}),
    "CS_DEP_PRDT_TYPE":  dict(map={"10": "보통예금", "20": "정기예금", "30": "적금"}),
    "CS_CNSNT_ITEM":     dict(map={"01": "마케팅수신", "02": "제3자제공", "03": "방카슈랑스"}),
    "CS_GNDR":           dict(map={"M": "남성", "F": "여성"}),
    "CS_JOB":            dict(map={"01": "급여소득", "02": "자영업", "03": "전문직", "04": "무직", "05": "기타"}),
    # ---- 의도된 결손 (레이어 미등재 — 세계 진실은 평가용 ground_truth로만) ----
    "CS_CHNL":      dict(map={"01": "영업점", "02": "모바일", "03": "인터넷", "04": "콜센터"}, layer=False),
    "CS_CNTC_TYPE": dict(map={"01": "전화상담", "02": "방문", "03": "채팅", "04": "민원"}, layer=False),
}

# ============================================================
# 테이블·컬럼 — C(이름, 타입, **opt)
#   opt: pk, fk="T.C", cs="CS_*", d="설명(저작)", cls="PII", null=True
#   d 없는 컬럼은 build에서 접미사 규칙으로 auto desc (source=auto, MEDIUM)
# ============================================================
def C(n, t, **k): return dict(n=n, t=t, **k)

AUDIT = [C("CREATED_AT", "TIMESTAMP", d="레코드 생성 시각."),
         C("UPDATED_BY", "VARCHAR(30)", null=True, d="레코드를 최종 수정한 사용자 ID.")]

TABLES = {
  # ---------------- CUSTOMER ----------------
  "CUST_BASE_INFO": dict(domain="CUSTOMER", grain="고객 1명", cols=[
      C("CUST_NO", "VARCHAR(15)", pk=True, d="고객을 식별하는 고유 번호."),
      C("CUST_NM", "VARCHAR(50)", cls="PII", d="고객 성명."),
      C("BIRTH_DT", "DATE", cls="PII", d="고객 생년월일."),
      C("GNDR_CD", "CHAR(1)", cs="CS_GNDR", d="고객 성별 코드."),
      C("JOB_CD", "CHAR(2)", cs="CS_JOB", d="고객 직업 분류 코드."),
      C("CUST_EMAIL", "VARCHAR(100)", null=True, cls="PII", d="고객 이메일 주소."),
      C("CUST_TEL_NO", "VARCHAR(20)", null=True, cls="PII", d="고객 연락처 전화번호."),
      C("REGION_CD", "VARCHAR(3)", cs="CS_REGION", d="고객의 관리 지역 코드."),
      C("CUST_GRD_CD", "CHAR(1)", cs="CS_CUST_GRD", d="거래 실적·기여도에 따른 고객 관계 등급 코드."),
      C("JOIN_DT", "DATE", d="고객이 최초 거래를 개시한 가입일."),
  ] + AUDIT),
  "CORP_CUST_INFO": dict(domain="CUSTOMER", grain="법인고객 1사", cols=[
      C("CORP_NO", "VARCHAR(15)", pk=True, d="법인고객을 식별하는 고유 번호."),
      C("CORP_NM", "VARCHAR(80)", d="법인명."),
      C("BIZ_REG_NO", "VARCHAR(12)", cls="PII", d="사업자등록번호."),
      C("CEO_NM", "VARCHAR(50)", cls="PII", d="대표자 성명."),
      C("ESTB_DT", "DATE", d="법인 설립일."),
      C("REGION_CD", "VARCHAR(3)", cs="CS_REGION", d="법인 소재 지역 코드."),
  ] + AUDIT),
  "CUST_GRD_HIST": dict(domain="CUSTOMER", grain="고객등급 변경 1건", cols=[
      C("GRD_HIST_NO", "VARCHAR(15)", pk=True),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("BFR_GRD_CD", "CHAR(1)", cs="CS_CUST_GRD", d="변경 전 고객등급 코드."),
      C("AFT_GRD_CD", "CHAR(1)", cs="CS_CUST_GRD", d="변경 후 고객등급 코드."),
      C("GRD_CHG_RSN_CD", "CHAR(2)", cs="CS_GRD_CHG_RSN", d="고객등급 변경 사유 코드."),
      C("GRD_CHG_DT", "DATE", d="고객등급이 변경된 일자."),
  ] + AUDIT),
  "CUST_ADDR_HIST": dict(domain="CUSTOMER", grain="주소 변경 1건", cols=[
      C("ADDR_HIST_NO", "VARCHAR(15)", pk=True),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("ADDR", "VARCHAR(200)", cls="PII", d="변경된 주소."),
      C("ZIP_CD", "CHAR(5)", d="우편번호."),
      C("REGION_CD", "VARCHAR(3)", cs="CS_REGION", d="주소 기준 지역 코드."),
      C("ADDR_CHG_DT", "DATE", d="주소가 변경된 일자."),
  ] + AUDIT),
  "CUST_CNSNT_INFO": dict(domain="CUSTOMER", grain="고객×동의항목 1건", cols=[
      C("CNSNT_NO", "VARCHAR(15)", pk=True),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("CNSNT_ITEM_CD", "CHAR(2)", cs="CS_CNSNT_ITEM", d="동의 항목 코드(마케팅수신·제3자제공 등)."),
      C("CNSNT_YN", "CHAR(1)", d="해당 항목 동의 여부(Y/N)."),
      C("CNSNT_DT", "DATE", d="동의 의사를 표시한 일자."),
      C("EXPR_DT", "DATE", null=True, d="동의 효력 만료 일자."),
  ] + AUDIT),
  "CUST_CNTC_HIST": dict(domain="CUSTOMER", grain="고객 접촉 1건", cols=[
      C("CNTC_NO", "VARCHAR(15)", pk=True),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("CNTC_TYPE_CD", "CHAR(2)", cs="CS_CNTC_TYPE", d="고객 접촉 유형 코드. 구체적 코드값 체계는 별도 확인 필요."),
      C("CNTC_DT", "DATE", d="고객 접촉이 발생한 일자."),
      C("CNTC_MEMO", "VARCHAR(500)", null=True, d="접촉 내용 메모."),
  ] + AUDIT),

  # ---------------- LOAN ----------------
  "LOAN_PRDT_MST": dict(domain="LOAN", grain="대출상품 1개", cols=[
      C("PRDT_CD", "VARCHAR(6)", pk=True, d="대출상품을 식별하는 상품 코드."),
      C("PRDT_NM", "VARCHAR(80)", d="대출상품명."),
      C("PRDT_TYPE_CD", "CHAR(2)", cs="CS_LOAN_PRDT_TYPE", d="대출상품 유형 코드(신용·담보·전세·정책)."),
      C("MAX_LMT_AMT", "DECIMAL(15,2)", d="상품의 최대 한도 금액(원)."),
      C("BASE_RATE", "DECIMAL(5,3)", d="상품 기준 금리(%)."),
      C("SALE_STRT_DT", "DATE", d="판매 개시일."),
      C("SALE_END_DT", "DATE", null=True, d="판매 종료일."),
  ] + AUDIT),
  "LOAN_APPL_HIST": dict(domain="LOAN", grain="대출신청 1건", cols=[
      C("LOAN_APPL_NO", "VARCHAR(20)", pk=True, d="대출신청 건을 식별하는 신청 번호."),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("PRDT_CD", "VARCHAR(6)", fk="LOAN_PRDT_MST.PRDT_CD"),
      C("LOAN_APPL_DT", "DATE", d="대출을 신청한 일자."),
      C("LOAN_AMT", "DECIMAL(15,2)", d="고객이 신청서에 기재한 대출 희망 금액(원)."),
      C("LOAN_TERM_MNTH", "SMALLINT", d="신청한 대출 기간(개월)."),
      C("APPL_STAT_CD", "CHAR(2)", cs="CS_LOAN_APPL_STAT", d="대출 신청 건의 처리 진행 상태 코드."),
      C("TAX_EXMP_FLG", "CHAR(1)", cs="CS_TAX_EXMP", d="대출 신청 건의 세금 면제 상태 코드."),
      C("TAX_EXMP_RSN_CD", "CHAR(2)", cs="CS_TAX_EXMP_RSN", d="세금 면제가 적용된 사유 코드."),
      C("BNS_CD", "CHAR(1)", cs="CS_BNS", d="방카슈랑스 안내·권유에 대한 동의 여부 코드."),
      C("CHNL_CD", "CHAR(2)", cs="CS_CHNL", d="대출 신청이 접수된 채널 코드. 구체적 코드값 체계는 별도 확인 필요."),
      C("CRDT_GRD_CD", "CHAR(2)", cs="CS_CRDT_GRD", d="심사 시점에 참조된 고객 신용등급 코드."),
      C("DCSN_DT", "DATE", null=True, d="승인/거절이 결정된 일자."),
  ] + AUDIT),
  "LOAN_ACCT_MST": dict(domain="LOAN", grain="대출계좌 1좌", cols=[
      C("LOAN_ACCT_NO", "VARCHAR(20)", pk=True, d="실행된 대출 계좌를 식별하는 계좌 번호."),
      C("LOAN_APPL_NO", "VARCHAR(20)", fk="LOAN_APPL_HIST.LOAN_APPL_NO"),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("PRDT_CD", "VARCHAR(6)", fk="LOAN_PRDT_MST.PRDT_CD"),
      C("DSBR_DT", "DATE", d="대출금이 실제 지급(실행)된 일자."),
      C("DSBR_AMT", "DECIMAL(15,2)", d="심사 후 실제로 실행(지급)된 대출 원금(원)."),
      C("LOAN_BAL_AMT", "DECIMAL(15,2)", d="대출 계좌의 미상환 원금 잔액(원)."),
      C("INT_RATE", "DECIMAL(5,3)", d="대출에 적용되는 연 이자율(%)."),
      C("LOAN_TERM_MNTH", "SMALLINT", d="대출 약정 기간(개월)."),
      C("LOAN_EXP_DT", "DATE", d="대출 계약이 종료되는 약정 만기 일자."),
      C("RPYMT_MTHD_CD", "CHAR(2)", cs="CS_LOAN_RPYMT_MTHD", d="대출 원리금의 상환 구조 코드."),
      C("ACCT_STAT_CD", "CHAR(2)", cs="CS_LOAN_ACCT_STAT", d="실행된 대출 계좌의 현재 상태 코드."),
      C("DLNQ_FLG", "CHAR(1)", d="대출 연체 여부 플래그(Y/N)."),
      C("DLNQ_DAYS", "INTEGER", d="연체 발생일로부터 경과한 일수(미연체 시 0)."),
  ] + AUDIT),
  "LOAN_RPYMT_SCHD": dict(domain="LOAN", grain="계좌×상환회차 1건", cols=[
      C("SCHD_NO", "VARCHAR(20)", pk=True),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("INSTL_NO", "SMALLINT", d="상환 회차 번호."),
      C("DUE_DT", "DATE", d="해당 회차의 약정 납부 기일."),
      C("DUE_PRNC_AMT", "DECIMAL(15,2)", d="해당 회차의 납부 예정 원금(원)."),
      C("DUE_INT_AMT", "DECIMAL(15,2)", d="해당 회차의 납부 예정 이자(원)."),
      C("PAID_YN", "CHAR(1)", d="해당 회차의 납부 완료 여부(Y/N)."),
  ] + AUDIT),
  "LOAN_RPYMT_HIST": dict(domain="LOAN", grain="상환거래 1건", cols=[
      C("RPYMT_NO", "VARCHAR(20)", pk=True, d="상환 거래를 식별하는 번호."),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("RPYMT_DT", "DATE", d="원리금이 납부된 일자."),
      C("RPYMT_AMT", "DECIMAL(15,2)", d="납부 총액(원금+이자, 원)."),
      C("PRNC_AMT", "DECIMAL(15,2)", d="납부액 중 원금 부분(원)."),
      C("INT_AMT", "DECIMAL(15,2)", d="납부액 중 이자 부분(원)."),
  ] + AUDIT),
  "LOAN_ERLY_RPYMT_HIST": dict(domain="LOAN", grain="중도상환 1건", cols=[
      C("ERLY_RPYMT_NO", "VARCHAR(20)", pk=True, d="중도상환 거래를 식별하는 번호."),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("ERLY_RPYMT_DT", "DATE", d="약정 스케줄보다 앞당겨 원금을 상환한 일자."),
      C("ERLY_RPYMT_AMT", "DECIMAL(15,2)", d="중도상환된 원금(원)."),
      C("ERLY_RPYMT_FEE", "DECIMAL(15,2)", d="중도상환 시 부과된 수수료(원)."),
  ] + AUDIT),
  "LOAN_DLNQ_HIST": dict(domain="LOAN", grain="연체발생 1건", cols=[
      C("DLNQ_NO", "VARCHAR(20)", pk=True),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("DLNQ_OCUR_DT", "DATE", d="연체가 발생한 일자."),
      C("DLNQ_RLS_DT", "DATE", null=True, d="연체가 해소(해제)된 일자."),
      C("DLNQ_AMT", "DECIMAL(15,2)", d="연체된 금액(원)."),
  ] + AUDIT),
  "LOAN_CLTRL_INFO": dict(domain="LOAN", grain="담보 1건", cols=[
      C("CLTRL_NO", "VARCHAR(20)", pk=True, d="담보를 식별하는 번호."),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("CLTRL_TYPE_CD", "CHAR(2)", cs="CS_CLTRL_TYPE", d="담보 자산의 유형 코드."),
      C("CLTRL_VAL_AMT", "DECIMAL(15,2)", d="담보 평가 금액(원)."),
      C("APRSL_DT", "DATE", d="담보 가치가 평가된 일자."),
  ] + AUDIT),
  "LOAN_GRNT_INFO": dict(domain="LOAN", grain="보증 1건", cols=[
      C("GRNT_NO", "VARCHAR(20)", pk=True, d="보증 계약을 식별하는 번호."),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("GRNT_ORG_NM", "VARCHAR(80)", d="보증을 제공한 기관명."),
      C("GRNT_AMT", "DECIMAL(15,2)", d="보증 금액(원)."),
      C("GRNT_RATE", "DECIMAL(5,2)", d="대출금 대비 보증 비율(%)."),
      C("GRNT_STRT_DT", "DATE", d="보증 효력 개시일."),
  ] + AUDIT),
  "LOAN_RATE_CHG_HIST": dict(domain="LOAN", grain="금리변경 1건", cols=[
      C("RATE_CHG_NO", "VARCHAR(20)", pk=True),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("BFR_RATE", "DECIMAL(5,3)", d="변경 전 적용 금리(%)."),
      C("AFT_RATE", "DECIMAL(5,3)", d="변경 후 적용 금리(%)."),
      C("RATE_CHG_DT", "DATE", d="금리가 변경된 일자."),
      C("RATE_CHG_RSN_CD", "CHAR(2)", cs="CS_RATE_CHG_RSN", d="금리 변경 사유 코드."),
  ] + AUDIT),
  "LOAN_EXTN_HIST": dict(domain="LOAN", grain="만기연장 1건", cols=[
      C("EXTN_NO", "VARCHAR(20)", pk=True, d="만기연장 처리를 식별하는 번호."),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("BFR_EXP_DT", "DATE", d="연장 전 만기 일자."),
      C("AFT_EXP_DT", "DATE", d="연장 후 만기 일자."),
      C("EXTN_DT", "DATE", d="만기연장이 처리된 일자."),
  ] + AUDIT),
  "LOAN_WRTOFF_HIST": dict(domain="LOAN", grain="상각처리 1건", cols=[
      C("WRTOFF_NO", "VARCHAR(20)", pk=True),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("WRTOFF_DT", "DATE", d="회수 불능으로 판단해 장부에서 손실 처리한 일자."),
      C("WRTOFF_AMT", "DECIMAL(15,2)", d="상각 처리된 금액(원)."),
  ] + AUDIT),
  "LOAN_INT_ACRL_HIST": dict(domain="LOAN", grain="계좌×월 이자발생 1건", cols=[
      C("ACRL_NO", "VARCHAR(20)", pk=True),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("ACRL_YM", "CHAR(6)", d="이자 발생 기준 연월(YYYYMM)."),
      C("ACRL_INT_AMT", "DECIMAL(15,2)", d="해당 월에 발생한 이자 금액(원)."),
  ] + AUDIT),

  # ---------------- CARD ----------------
  "CARD_PRDT_MST": dict(domain="CARD", grain="카드상품 1개", cols=[
      C("CARD_PRDT_CD", "VARCHAR(6)", pk=True, d="카드상품을 식별하는 상품 코드."),
      C("CARD_PRDT_NM", "VARCHAR(80)", d="카드상품명."),
      C("ANNL_FEE", "DECIMAL(10,2)", d="연회비(원)."),
  ] + AUDIT),
  "CARD_APPL_HIST": dict(domain="CARD", grain="카드신청 1건", cols=[
      C("CARD_APPL_NO", "VARCHAR(20)", pk=True, d="카드 발급 신청 건을 식별하는 번호."),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("CARD_PRDT_CD", "VARCHAR(6)", fk="CARD_PRDT_MST.CARD_PRDT_CD"),
      C("CARD_APPL_DT", "DATE", d="카드 발급을 신청한 일자."),
      C("APRV_YN", "CHAR(1)", d="발급 승인 여부(Y/N)."),
  ] + AUDIT),
  "CARD_MST": dict(domain="CARD", grain="카드 1장", cols=[
      C("CARD_NO", "VARCHAR(20)", pk=True, d="카드를 식별하는 카드 번호.", cls="PII"),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("CARD_PRDT_CD", "VARCHAR(6)", fk="CARD_PRDT_MST.CARD_PRDT_CD"),
      C("CARD_GRD_CD", "CHAR(1)", cs="CS_CARD_GRD", d="카드 상품의 등급 코드."),
      C("CARD_STAT_CD", "CHAR(1)", cs="CS_CARD_STAT", d="카드의 현재 상태 코드."),
      C("USE_LMT_AMT", "DECIMAL(15,2)", d="카드의 월간 이용 가능 한도 금액(원)."),
      C("ISSU_DT", "DATE", d="카드가 발급된 일자."),
      C("EXP_YM", "CHAR(6)", d="카드 유효기간 만료 연월(YYYYMM)."),
  ] + AUDIT),
  "CARD_SLS_HIST": dict(domain="CARD", grain="승인/매출 1건", cols=[
      C("SLS_NO", "VARCHAR(20)", pk=True, d="카드 승인(매출) 거래를 식별하는 번호."),
      C("CARD_NO", "VARCHAR(20)", fk="CARD_MST.CARD_NO"),
      C("MRCHT_NO", "VARCHAR(15)", fk="MRCHT_INFO.MRCHT_NO"),
      C("APRV_DT", "DATE", d="카드 승인이 발생한 일자."),
      C("SLS_AMT", "DECIMAL(15,2)", d="승인(매출) 금액(원)."),
      C("INSTL_MNTH", "SMALLINT", d="할부 개월 수(일시불은 0)."),
      C("CNCL_YN", "CHAR(1)", d="승인 취소 여부(Y/N)."),
  ] + AUDIT),
  "CARD_BILL_HIST": dict(domain="CARD", grain="카드×청구월 1건", cols=[
      C("BILL_NO", "VARCHAR(20)", pk=True, d="청구 건을 식별하는 번호."),
      C("CARD_NO", "VARCHAR(20)", fk="CARD_MST.CARD_NO"),
      C("BILL_YM", "CHAR(6)", d="청구 기준 연월(YYYYMM)."),
      C("BILL_DT", "DATE", d="청구서가 확정·발행된 일자."),
      C("BILL_AMT", "DECIMAL(15,2)", d="청구월에 결제 대상으로 확정된 금액(원)."),
      C("RPYMT_MTHD_CD", "CHAR(1)", cs="CS_CARD_RPYMT_MTHD", d="카드 대금의 결제 방식 코드."),
      C("DLNQ_FLG", "CHAR(1)", d="카드 청구 대금의 연체 여부 플래그(Y/N)."),
      C("MIN_PAY_AMT", "DECIMAL(15,2)", d="리볼빙 시 최소 결제 금액(원)."),
  ] + AUDIT),
  "CARD_RPYMT_HIST": dict(domain="CARD", grain="결제 1건", cols=[
      C("CARD_RPYMT_NO", "VARCHAR(20)", pk=True),
      C("BILL_NO", "VARCHAR(20)", fk="CARD_BILL_HIST.BILL_NO"),
      C("RPYMT_DT", "DATE", d="카드 대금이 결제된 일자."),
      C("RPYMT_AMT", "DECIMAL(15,2)", d="결제된 금액(원)."),
  ] + AUDIT),
  "CARD_LMT_HIST": dict(domain="CARD", grain="한도변경 1건", cols=[
      C("LMT_CHG_NO", "VARCHAR(20)", pk=True),
      C("CARD_NO", "VARCHAR(20)", fk="CARD_MST.CARD_NO"),
      C("BFR_LMT_AMT", "DECIMAL(15,2)", d="변경 전 이용 한도(원)."),
      C("AFT_LMT_AMT", "DECIMAL(15,2)", d="변경 후 이용 한도(원)."),
      C("LMT_CHG_RSN_CD", "CHAR(2)", cs="CS_LMT_CHG_RSN", d="한도 변경 사유 코드."),
      C("LMT_CHG_DT", "DATE", d="한도가 변경된 일자."),
  ] + AUDIT),
  "MRCHT_INFO": dict(domain="CARD", grain="가맹점 1개", cols=[
      C("MRCHT_NO", "VARCHAR(15)", pk=True, d="가맹점을 식별하는 고유 번호."),
      C("MRCHT_NM", "VARCHAR(80)", d="가맹점 상호명."),
      C("BIZ_TYPE_CD", "CHAR(2)", cs="CS_BIZ_TYPE", d="가맹점의 업종 분류 코드."),
      C("REGION_CD", "VARCHAR(3)", cs="CS_REGION", d="가맹점 소재 지역 코드."),
  ] + AUDIT),

  # ---------------- DEPOSIT ----------------
  "DEP_PRDT_MST": dict(domain="DEPOSIT", grain="수신상품 1개", cols=[
      C("DEP_PRDT_CD", "VARCHAR(6)", pk=True, d="수신상품을 식별하는 상품 코드."),
      C("DEP_PRDT_NM", "VARCHAR(80)", d="수신상품명."),
      C("DEP_PRDT_TYPE_CD", "CHAR(2)", cs="CS_DEP_PRDT_TYPE", d="수신상품 유형 코드(보통예금·정기예금·적금)."),
      C("BASE_INT_RATE", "DECIMAL(5,3)", d="상품 기준 금리(%)."),
  ] + AUDIT),
  "DEP_ACCT_MST": dict(domain="DEPOSIT", grain="수신계좌 1좌", cols=[
      C("DEP_ACCT_NO", "VARCHAR(20)", pk=True, d="수신 계좌를 식별하는 계좌 번호."),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("DEP_PRDT_CD", "VARCHAR(6)", fk="DEP_PRDT_MST.DEP_PRDT_CD"),
      C("ACCT_STAT_CD", "CHAR(2)", cs="CS_DEP_ACCT_STAT", d="수신 계좌의 현재 상태 코드."),
      C("ACCT_BAL_AMT", "DECIMAL(15,2)", d="수신 계좌의 현재 잔액(원)."),
      C("OPEN_DT", "DATE", d="계좌가 개설된 일자."),
      C("MTRT_DT", "DATE", null=True, d="정기예금·적금의 약정 만기 일자(보통예금은 없음)."),
  ] + AUDIT),
  "DEP_TXN_HIST": dict(domain="DEPOSIT", grain="입출금거래 1건", cols=[
      C("TXN_NO", "VARCHAR(20)", pk=True, d="입출금 거래를 식별하는 번호."),
      C("DEP_ACCT_NO", "VARCHAR(20)", fk="DEP_ACCT_MST.DEP_ACCT_NO"),
      C("TXN_DT", "DATE", d="거래가 발생한 일자."),
      C("TXN_TYPE_CD", "CHAR(1)", cs="CS_DEP_TXN_TYPE", d="거래 유형 코드(입금/출금)."),
      C("TXN_AMT", "DECIMAL(15,2)", d="거래 금액(원)."),
      C("AFT_BAL_AMT", "DECIMAL(15,2)", d="거래 후 계좌 잔액(원)."),
  ] + AUDIT),
  "DEP_INT_PAY_HIST": dict(domain="DEPOSIT", grain="이자지급 1건", cols=[
      C("INT_PAY_NO", "VARCHAR(20)", pk=True),
      C("DEP_ACCT_NO", "VARCHAR(20)", fk="DEP_ACCT_MST.DEP_ACCT_NO"),
      C("INT_PAY_DT", "DATE", d="예금 이자가 지급된 일자."),
      C("INT_PAY_AMT", "DECIMAL(15,2)", d="지급된 이자 금액(원)."),
  ] + AUDIT),
  "DEP_ACCT_CLS_HIST": dict(domain="DEPOSIT", grain="해지처리 1건", cols=[
      C("CLS_NO", "VARCHAR(20)", pk=True),
      C("DEP_ACCT_NO", "VARCHAR(20)", fk="DEP_ACCT_MST.DEP_ACCT_NO"),
      C("CLS_DT", "DATE", d="수신 계좌가 해지된 일자."),
      C("CLS_RSN_CD", "CHAR(2)", cs="CS_CLS_RSN", d="해지 사유 코드."),
      C("RFND_AMT", "DECIMAL(15,2)", d="해지 시 고객에게 환급된 금액(원)."),
  ] + AUDIT),

  # ---------------- RISK ----------------
  "CRDT_EVAL_HIST": dict(domain="RISK", grain="신용평가 1건", cols=[
      C("EVAL_NO", "VARCHAR(20)", pk=True, d="신용평가 수행 건을 식별하는 번호."),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("EVAL_DT", "DATE", d="신용평가가 수행된 일자."),
      C("CRDT_GRD_CD", "CHAR(2)", cs="CS_CRDT_GRD", d="평가로 산정된 신용 위험 등급 코드(1~10, 낮을수록 우량)."),
      C("CRDT_SCR", "INTEGER", d="평가로 산정된 수치형 신용 점수(0~1000)."),
      C("EVAL_MODEL_VER", "VARCHAR(10)", d="평가에 사용된 모델 버전."),
  ] + AUDIT),
  "CRDT_LMT_INFO": dict(domain="RISK", grain="고객×여신한도 1건", cols=[
      C("LMT_NO", "VARCHAR(20)", pk=True),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("CRDT_LMT_AMT", "DECIMAL(15,2)", d="고객에게 부여된 총 여신 공여 한도 금액(원)."),
      C("USED_AMT", "DECIMAL(15,2)", d="현재 사용 중인 여신 금액(원)."),
      C("LMT_SET_DT", "DATE", d="여신한도가 설정·갱신된 일자."),
  ] + AUDIT),
  "RISK_EXPSR_INFO": dict(domain="RISK", grain="고객×익스포저 1건", cols=[
      C("EXPSR_NO", "VARCHAR(20)", pk=True),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("EXPSR_AMT", "DECIMAL(15,2)", d="해당 기준월의 신용 익스포저 금액(원)."),
      C("EXPSR_YM", "CHAR(6)", d="익스포저 산정 기준 연월(YYYYMM)."),
  ] + AUDIT),
  "FRAUD_DTCT_HIST": dict(domain="RISK", grain="이상거래탐지 1건", cols=[
      C("DTCT_NO", "VARCHAR(20)", pk=True, d="이상거래 탐지 건을 식별하는 번호."),
      C("CUST_NO", "VARCHAR(15)", fk="CUST_BASE_INFO.CUST_NO"),
      C("DTCT_DT", "DATE", d="이상거래가 탐지된 일자."),
      C("DTCT_TYPE_CD", "CHAR(2)", cs="CS_FRAUD_TYPE", d="탐지된 이상거래 유형 코드."),
      C("PROC_STAT_CD", "CHAR(2)", cs="CS_FRAUD_PROC", d="탐지 건의 처리 상태 코드."),
  ] + AUDIT),
  "PROV_CALC_HIST": dict(domain="RISK", grain="계좌×월 충당금산정 1건", cols=[
      C("PROV_NO", "VARCHAR(20)", pk=True),
      C("LOAN_ACCT_NO", "VARCHAR(20)", fk="LOAN_ACCT_MST.LOAN_ACCT_NO"),
      C("CALC_YM", "CHAR(6)", d="충당금 산정 기준 연월(YYYYMM)."),
      C("PROV_AMT", "DECIMAL(15,2)", d="예상 손실에 대비해 적립한 충당금 금액(원)."),
      C("PROV_RATE", "DECIMAL(5,2)", d="잔액 대비 충당금 적립 비율(%)."),
  ] + AUDIT),
}

# ============================================================
# 개념 — case: normal | family:Fx | granularity | boundary:*
# real 키: stored_as / measured_by / identified_by / attribute_of /
#          dated_by / segmented_by / expressed_as(D6)
# layer="EXCLUDED" 면 Term 미등재(세계에만 존재).
# ============================================================
CONCEPTS = [
  # ===== F1 등급 =====
  dict(name="신용등급", domain="RISK", family="F1_grade",
       d="신용평가로 산정되는 고객의 신용 위험 등급 (1~10, 낮을수록 우량)", syn=["신용도등급"],
       real=dict(stored_as="CRDT_EVAL_HIST.CRDT_GRD_CD", dated_by="CRDT_EVAL_HIST.EVAL_DT"),
       cs="CS_CRDT_GRD", case="family:F1_grade"),
  dict(name="고객등급", domain="CUSTOMER", family="F1_grade",
       d="거래 실적·기여도에 따른 고객 관계 등급 (VIP·골드·실버·일반)", syn=["회원등급"],
       real=dict(stored_as="CUST_BASE_INFO.CUST_GRD_CD",
                 attribute_of=["CUST_GRD_HIST.GRD_CHG_RSN_CD"], dated_by="CUST_GRD_HIST.GRD_CHG_DT"),
       cs="CS_CUST_GRD", case="family:F1_grade"),
  dict(name="카드등급", domain="CARD", family="F1_grade",
       d="카드 상품의 등급 (플래티넘·골드·클래식)",
       real=dict(stored_as="CARD_MST.CARD_GRD_CD"), cs="CS_CARD_GRD", case="family:F1_grade"),

  # ===== F2 상태 =====
  dict(name="대출신청상태", domain="LOAN", family="F2_status",
       d="대출 신청 건의 처리 진행 상태 (접수~승인/거절/취소)", syn=["신청상태", "대출상태"],
       real=dict(stored_as="LOAN_APPL_HIST.APPL_STAT_CD"), cs="CS_LOAN_APPL_STAT",
       case="family:F2_status,granularity"),
  dict(name="대출계좌상태", domain="LOAN", family="F2_status",
       d="실행된 대출 계좌의 현재 상태 (정상~완제)", syn=["계좌상태", "대출상태"],
       real=dict(stored_as="LOAN_ACCT_MST.ACCT_STAT_CD"), cs="CS_LOAN_ACCT_STAT",
       case="family:F2_status,granularity"),
  dict(name="카드상태", domain="CARD", family="F2_status",
       d="카드의 현재 상태 (정상·정지·해지·분실)",
       real=dict(stored_as="CARD_MST.CARD_STAT_CD"), cs="CS_CARD_STAT", case="family:F2_status"),
  dict(name="수신계좌상태", domain="DEPOSIT", family="F2_status",
       d="수신 계좌의 현재 상태 (신규~해지)", syn=["계좌상태"],
       real=dict(stored_as="DEP_ACCT_MST.ACCT_STAT_CD"), cs="CS_DEP_ACCT_STAT", case="family:F2_status"),
  dict(name="기한이익상실", domain="LOAN", family="F2_status",
       d="채무자 사유로 만기 전 대출 전액의 상환 의무가 발생한 상태", syn=["기이상", "EOD"],
       real=dict(expressed_as=dict(column="LOAN_ACCT_MST.ACCT_STAT_CD", value="03")), case="normal"),
  dict(name="상각", domain="LOAN", family="F2_status",
       d="회수 불능으로 판단해 장부에서 손실 처리한 상태", syn=["대손상각"],
       real=dict(expressed_as=dict(column="LOAN_ACCT_MST.ACCT_STAT_CD", value="04"),
                 attribute_of=["LOAN_WRTOFF_HIST.WRTOFF_AMT"], dated_by="LOAN_WRTOFF_HIST.WRTOFF_DT"),
       case="normal"),
  dict(name="완제", domain="LOAN",
       d="대출 원리금을 전액 상환해 계좌가 종결된 상태", syn=["상환완료", "전액상환"],
       real=dict(expressed_as=dict(column="LOAN_ACCT_MST.ACCT_STAT_CD", value="05")), case="normal"),
  dict(name="해지", domain=None, family="F2_status",
       d="계약 관계를 종료하는 행위 — 수신계좌 해지와 카드 해지가 별개로 실현",
       real=dict(expressed_as=[dict(column="DEP_ACCT_MST.ACCT_STAT_CD", value="40", domain="DEPOSIT"),
                               dict(column="CARD_MST.CARD_STAT_CD", value="T", domain="CARD")],
                 dated_by="DEP_ACCT_CLS_HIST.CLS_DT"),
       case="family:F2_status", ambiguous=True),

  # ===== F3 상환/결제방식 =====
  dict(name="대출상환방식", domain="LOAN", family="F3_repayment",
       d="대출 원리금의 상환 구조 (원리금균등·원금균등·만기일시)", syn=["상환방식"],
       real=dict(stored_as="LOAN_ACCT_MST.RPYMT_MTHD_CD"), cs="CS_LOAN_RPYMT_MTHD",
       case="family:F3_repayment"),
  dict(name="카드결제방식", domain="CARD", family="F3_repayment",
       d="카드 대금의 결제 방식 (일시불·할부·리볼빙)", syn=["결제방식", "상환방식"],
       real=dict(stored_as="CARD_BILL_HIST.RPYMT_MTHD_CD"), cs="CS_CARD_RPYMT_MTHD",
       case="family:F3_repayment"),
  dict(name="리볼빙", domain="CARD",
       d="카드 대금 일부만 결제하고 잔액을 이월하는 결제 방식", syn=["일부결제금액이월약정"],
       real=dict(expressed_as=dict(column="CARD_BILL_HIST.RPYMT_MTHD_CD", value="3"),
                 attribute_of=["CARD_BILL_HIST.MIN_PAY_AMT"], measured_by="M_REVOLVING_RATE"), case="normal"),
  dict(name="할부", domain="CARD",
       d="카드 매출 대금을 여러 달에 나누어 결제하는 방식",
       real=dict(expressed_as=dict(column="CARD_BILL_HIST.RPYMT_MTHD_CD", value="2"),
                 attribute_of=["CARD_SLS_HIST.INSTL_MNTH"]), case="normal"),

  # ===== F4 한도 =====
  dict(name="여신한도", domain="RISK", family="F4_limit",
       d="고객에게 부여된 총 여신(대출) 공여 한도 금액", syn=["대출한도", "신용공여한도"],
       real=dict(stored_as="CRDT_LMT_INFO.CRDT_LMT_AMT",
                 attribute_of=["CRDT_LMT_INFO.USED_AMT"], dated_by="CRDT_LMT_INFO.LMT_SET_DT"),
       case="family:F4_limit"),
  dict(name="카드이용한도", domain="CARD", family="F4_limit",
       d="카드의 월간 이용 가능 한도 금액", syn=["카드한도", "이용한도"],
       real=dict(stored_as="CARD_MST.USE_LMT_AMT",
                 attribute_of=["CARD_LMT_HIST.LMT_CHG_RSN_CD"], dated_by="CARD_LMT_HIST.LMT_CHG_DT"),
       case="family:F4_limit"),

  # ===== F5 연체 =====
  dict(name="대출연체", domain="LOAN", family="F5_dlnq",
       d="대출 상환 의무를 약정일까지 이행하지 않은 상태", syn=["연체"],
       real=dict(stored_as="LOAN_ACCT_MST.DLNQ_FLG", measured_by="M_LOAN_DLNQ_RATE",
                 attribute_of=["LOAN_ACCT_MST.DLNQ_DAYS", "LOAN_DLNQ_HIST.DLNQ_AMT"],
                 dated_by="LOAN_DLNQ_HIST.DLNQ_OCUR_DT"),
       case="family:F5_dlnq", ambiguous=True),
  dict(name="카드연체", domain="CARD", family="F5_dlnq",
       d="카드 청구 대금을 결제일까지 납부하지 않은 상태", syn=["연체"],
       real=dict(stored_as="CARD_BILL_HIST.DLNQ_FLG", measured_by="M_CARD_DLNQ_RATE",
                 dated_by="CARD_BILL_HIST.BILL_DT"),
       case="family:F5_dlnq", ambiguous=True),
  dict(name="연체일수", domain="LOAN",
       d="연체 발생일로부터 경과한 일수",
       real=dict(stored_as="LOAN_ACCT_MST.DLNQ_DAYS"), case="normal"),
  dict(name="연체해소", domain="LOAN",
       d="발생했던 연체가 납부로 해제된 사건", syn=["연체해제"],
       real=dict(dated_by="LOAN_DLNQ_HIST.DLNQ_RLS_DT"), case="normal"),

  # ===== F6 잔액 =====
  dict(name="대출잔액", domain="LOAN", family="F6_balance",
       d="대출 계좌의 미상환 원금 잔액", syn=["잔액", "잔고", "대출잔고"],
       real=dict(stored_as="LOAN_ACCT_MST.LOAN_BAL_AMT", measured_by="M_TOTAL_LOAN_BAL"),
       case="family:F6_balance", ambiguous=True),
  dict(name="예금잔액", domain="DEPOSIT", family="F6_balance",
       d="수신 계좌의 현재 잔액", syn=["잔액", "잔고", "계좌잔액"],
       real=dict(stored_as="DEP_ACCT_MST.ACCT_BAL_AMT", measured_by="M_DEP_AVG_BAL"),
       case="family:F6_balance", ambiguous=True),

  # ===== F7 만기 (드라이런 F-3) =====
  dict(name="대출만기", domain="LOAN", family="F7_maturity",
       d="대출 계약이 종료되는 약정 시점", syn=["만기", "만기일"],
       real=dict(dated_by="LOAN_ACCT_MST.LOAN_EXP_DT", attribute_of=["LOAN_ACCT_MST.LOAN_TERM_MNTH"]),
       case="family:F7_maturity", ambiguous=True),
  dict(name="예금만기", domain="DEPOSIT", family="F7_maturity",
       d="정기예금·적금의 약정이 종료되는 시점", syn=["만기", "만기일"],
       real=dict(dated_by="DEP_ACCT_MST.MTRT_DT"),
       case="family:F7_maturity", ambiguous=True),

  # ===== 엔티티 =====
  dict(name="고객", domain="CUSTOMER",
       d="은행과 거래 관계에 있는 개인", syn=["Customer", "Client", "회원"],
       real=dict(identified_by="CUST_BASE_INFO.CUST_NO",
                 attribute_of=["CUST_BASE_INFO.CUST_NM", "CUST_BASE_INFO.BIRTH_DT"],
                 dated_by="CUST_BASE_INFO.JOIN_DT"), case="normal"),
  dict(name="법인고객", domain="CUSTOMER",
       d="은행과 거래 관계에 있는 법인", syn=["기업고객"],
       real=dict(identified_by="CORP_CUST_INFO.CORP_NO", dated_by="CORP_CUST_INFO.ESTB_DT"), case="normal"),
  dict(name="대출계좌", domain="LOAN",
       d="실행된 대출 1건의 관리 단위", syn=["대출좌", "여신계좌"],
       real=dict(identified_by="LOAN_ACCT_MST.LOAN_ACCT_NO", dated_by="LOAN_ACCT_MST.DSBR_DT"), case="normal"),
  dict(name="대출신청", domain="LOAN",
       d="고객이 대출을 신청한 건",
       real=dict(identified_by="LOAN_APPL_HIST.LOAN_APPL_NO", dated_by="LOAN_APPL_HIST.LOAN_APPL_DT",
                 measured_by="M_APRV_RATE"),
       case="normal"),
  dict(name="가맹점", domain="CARD",
       d="카드 결제를 받는 사업장",
       real=dict(identified_by="MRCHT_INFO.MRCHT_NO", segmented_by="MRCHT_INFO.BIZ_TYPE_CD"), case="normal"),
  dict(name="수신계좌", domain="DEPOSIT",
       d="예금·적금 등 수신 거래의 계좌 단위", syn=["예금계좌"],
       real=dict(identified_by="DEP_ACCT_MST.DEP_ACCT_NO", dated_by="DEP_ACCT_MST.OPEN_DT"), case="normal"),
  dict(name="카드", domain="CARD",
       d="고객에게 발급된 카드 1장",
       real=dict(identified_by="CARD_MST.CARD_NO", dated_by="CARD_MST.ISSU_DT"), case="normal"),

  # ===== LOAN 핵심 =====
  dict(name="대출신청금액", domain="LOAN",
       d="고객이 신청서에 기재한 대출 희망 금액", syn=["신청금액", "대출금액"],
       real=dict(stored_as="LOAN_APPL_HIST.LOAN_AMT"), case="granularity", ambiguous=True),
  dict(name="대출실행금액", domain="LOAN",
       d="심사 후 실제로 실행(지급)된 대출 원금", syn=["실행금액", "대출금액"],
       real=dict(stored_as="LOAN_ACCT_MST.DSBR_AMT", dated_by="LOAN_ACCT_MST.DSBR_DT"),
       case="granularity", ambiguous=True),
  dict(name="대출실행", domain="LOAN",
       d="승인된 대출의 자금이 지급되는 사건", syn=["실행", "기표"],
       real=dict(dated_by="LOAN_ACCT_MST.DSBR_DT"), case="normal"),
  dict(name="금리", domain="LOAN",
       d="대출에 적용되는 연 이자율", syn=["이자율", "적용금리", "대출금리"],
       real=dict(stored_as="LOAN_ACCT_MST.INT_RATE", measured_by="M_AVG_INT_RATE",
                 attribute_of=["LOAN_RATE_CHG_HIST.BFR_RATE", "LOAN_RATE_CHG_HIST.AFT_RATE"],
                 dated_by="LOAN_RATE_CHG_HIST.RATE_CHG_DT"), case="normal"),
  dict(name="만기연장", domain="LOAN",
       d="약정 만기를 연장하는 처리", syn=["기한연장", "연장"],
       real=dict(identified_by="LOAN_EXTN_HIST.EXTN_NO", dated_by="LOAN_EXTN_HIST.EXTN_DT",
                 attribute_of=["LOAN_EXTN_HIST.BFR_EXP_DT", "LOAN_EXTN_HIST.AFT_EXP_DT"]), case="normal"),
  dict(name="상환", domain="LOAN",
       d="대출 원리금을 납부하는 거래", syn=["납부", "변제"],
       real=dict(identified_by="LOAN_RPYMT_HIST.RPYMT_NO", dated_by="LOAN_RPYMT_HIST.RPYMT_DT",
                 attribute_of=["LOAN_RPYMT_HIST.RPYMT_AMT", "LOAN_RPYMT_HIST.PRNC_AMT",
                               "LOAN_RPYMT_HIST.INT_AMT"]), case="normal"),
  dict(name="상환스케줄", domain="LOAN",
       d="대출의 회차별 약정 납부 계획", syn=["상환계획"],
       real=dict(identified_by="LOAN_RPYMT_SCHD.SCHD_NO", dated_by="LOAN_RPYMT_SCHD.DUE_DT",
                 attribute_of=["LOAN_RPYMT_SCHD.INSTL_NO", "LOAN_RPYMT_SCHD.DUE_PRNC_AMT"]), case="normal"),
  dict(name="미납회차", domain="LOAN",
       d="약정 기일이 지났으나 납부되지 않은 상환 회차",
       real=dict(expressed_as=dict(column="LOAN_RPYMT_SCHD.PAID_YN", value="N")), case="normal"),
  dict(name="중도상환", domain="LOAN",
       d="약정 스케줄보다 앞당겨 원금을 상환하는 거래", syn=["조기상환", "선상환"],
       real=dict(identified_by="LOAN_ERLY_RPYMT_HIST.ERLY_RPYMT_NO",
                 dated_by="LOAN_ERLY_RPYMT_HIST.ERLY_RPYMT_DT",
                 attribute_of=["LOAN_ERLY_RPYMT_HIST.ERLY_RPYMT_AMT"], measured_by="M_ERLY_RPYMT_RATE"), case="normal"),
  dict(name="세금면제", domain="LOAN",
       d="대출 건에 세금이 부과되지 않는 상태", syn=["면세", "비과세"],
       real=dict(stored_as="LOAN_APPL_HIST.TAX_EXMP_FLG",
                 attribute_of=["LOAN_APPL_HIST.TAX_EXMP_RSN_CD"]),
       cs="CS_TAX_EXMP", case="normal"),
  dict(name="면제사유", domain="LOAN",
       d="세금 면제가 적용된 근거 사유", syn=["세금면제사유"],
       real=dict(stored_as="LOAN_APPL_HIST.TAX_EXMP_RSN_CD",
                 segmented_by="LOAN_APPL_HIST.TAX_EXMP_RSN_CD"), cs="CS_TAX_EXMP_RSN", case="normal"),
  dict(name="담보", domain="LOAN",
       d="대출 채권 보전을 위해 제공된 자산",
       real=dict(identified_by="LOAN_CLTRL_INFO.CLTRL_NO", segmented_by="LOAN_CLTRL_INFO.CLTRL_TYPE_CD",
                 attribute_of=["LOAN_CLTRL_INFO.CLTRL_VAL_AMT"], dated_by="LOAN_CLTRL_INFO.APRSL_DT"),
       case="normal"),
  dict(name="담보유형", domain="LOAN",
       d="담보 자산의 종류 구분 (아파트·토지 등)",
       real=dict(segmented_by="LOAN_CLTRL_INFO.CLTRL_TYPE_CD"), cs="CS_CLTRL_TYPE", case="normal"),
  dict(name="보증", domain="LOAN",
       d="제3자가 채무 이행을 담보하는 계약", syn=["보증서", "지급보증"],
       real=dict(identified_by="LOAN_GRNT_INFO.GRNT_NO",
                 attribute_of=["LOAN_GRNT_INFO.GRNT_AMT", "LOAN_GRNT_INFO.GRNT_RATE",
                               "LOAN_GRNT_INFO.GRNT_ORG_NM"]), case="normal"),
  dict(name="이자수익", domain="LOAN",
       d="대출에서 월별로 발생하는 이자 수익", syn=["발생이자"],
       real=dict(stored_as="LOAN_INT_ACRL_HIST.ACRL_INT_AMT"), case="normal"),
  dict(name="대출상품", domain="LOAN",
       d="판매되는 대출 상품의 단위", syn=["상품", "여신상품"],
       real=dict(identified_by="LOAN_PRDT_MST.PRDT_CD", segmented_by="LOAN_APPL_HIST.PRDT_CD"),
       case="normal"),
  dict(name="정책대출", domain="LOAN",
       d="정부 정책에 따라 공급되는 대출 상품", syn=["정책금융"],
       real=dict(expressed_as=dict(column="LOAN_PRDT_MST.PRDT_TYPE_CD", value="04")), case="normal"),
  dict(name="담보대출", domain="LOAN",
       d="담보를 설정하고 실행되는 대출",
       real=dict(expressed_as=dict(column="LOAN_PRDT_MST.PRDT_TYPE_CD", value="02")), case="normal"),
  dict(name="신용대출", domain="LOAN",
       d="담보 없이 신용으로 실행되는 대출",
       real=dict(expressed_as=dict(column="LOAN_PRDT_MST.PRDT_TYPE_CD", value="01")), case="normal"),
  dict(name="방카슈랑스동의", domain="LOAN",
       d="대출 신청 시 방카슈랑스 안내·권유에 대한 동의 여부",
       real=dict(stored_as="LOAN_APPL_HIST.BNS_CD", measured_by="M_BNS_CNSNT_RATE"),
       cs="CS_BNS", case="normal"),
  dict(name="신청채널", domain="LOAN",
       d="대출 신청이 접수된 채널 (영업점·모바일 등 — 코드값 사전 의도 결손)",
       real=dict(stored_as="LOAN_APPL_HIST.CHNL_CD", segmented_by="LOAN_APPL_HIST.CHNL_CD"),
       cs="CS_CHNL", case="boundary:no_codedict",
       expected="코드값 추측 금지 — 사전 부재 보고 또는 값 라벨 확인 요청"),

  # ===== 차원 =====
  dict(name="지역", domain="CUSTOMER",
       d="고객·가맹점의 관리 지역 구분",
       real=dict(segmented_by="CUST_BASE_INFO.REGION_CD"), cs="CS_REGION", case="normal"),
  dict(name="업종", domain="CARD",
       d="가맹점의 업종 분류",
       real=dict(segmented_by="MRCHT_INFO.BIZ_TYPE_CD"), cs="CS_BIZ_TYPE", case="normal"),
  dict(name="성별", domain="CUSTOMER",
       d="고객의 성별 구분",
       real=dict(segmented_by="CUST_BASE_INFO.GNDR_CD"), cs="CS_GNDR", case="normal"),
  dict(name="직업", domain="CUSTOMER",
       d="고객의 직업 분류",
       real=dict(segmented_by="CUST_BASE_INFO.JOB_CD"), cs="CS_JOB", case="normal"),

  # ===== CUSTOMER 보조 =====
  dict(name="마케팅수신동의", domain="CUSTOMER",
       d="마케팅 정보 수신에 대한 고객 동의", syn=["마케팅동의"],
       real=dict(expressed_as=dict(column="CUST_CNSNT_INFO.CNSNT_ITEM_CD", value="01"),
                 dated_by="CUST_CNSNT_INFO.CNSNT_DT", measured_by="M_MKT_CNSNT_RATE"), case="normal"),
  dict(name="고객접촉", domain="CUSTOMER",
       d="상담·방문 등 고객과의 접촉 이력", syn=["상담이력"],
       real=dict(identified_by="CUST_CNTC_HIST.CNTC_NO", dated_by="CUST_CNTC_HIST.CNTC_DT",
                 segmented_by="CUST_CNTC_HIST.CNTC_TYPE_CD"),
       cs="CS_CNTC_TYPE", case="boundary:no_codedict",
       expected="접촉 유형별 분석 요청 시 코드값 추측 금지 — 사전 부재 보고"),
  dict(name="주소변경", domain="CUSTOMER",
       d="고객 주소가 변경된 사건",
       real=dict(dated_by="CUST_ADDR_HIST.ADDR_CHG_DT"), case="normal"),
  dict(name="가입", domain="CUSTOMER",
       d="고객이 최초 거래를 개시한 사건", syn=["신규가입", "거래개시"],
       real=dict(dated_by="CUST_BASE_INFO.JOIN_DT"), case="normal"),

  # ===== CARD 보조 =====
  dict(name="카드발급", domain="CARD",
       d="카드가 발급된 사건", syn=["발급"],
       real=dict(dated_by="CARD_MST.ISSU_DT"), case="normal"),
  dict(name="카드매출", domain="CARD",
       d="카드 승인으로 발생한 매출 거래", syn=["카드승인", "카드사용"],
       real=dict(identified_by="CARD_SLS_HIST.SLS_NO", dated_by="CARD_SLS_HIST.APRV_DT",
                 attribute_of=["CARD_SLS_HIST.SLS_AMT"]), case="normal"),
  dict(name="승인취소", domain="CARD",
       d="카드 승인이 취소된 거래", syn=["매출취소"],
       real=dict(expressed_as=dict(column="CARD_SLS_HIST.CNCL_YN", value="Y")), case="normal"),
  dict(name="청구금액", domain="CARD",
       d="청구월에 결제 대상으로 확정된 금액", syn=["청구액"],
       real=dict(stored_as="CARD_BILL_HIST.BILL_AMT", dated_by="CARD_BILL_HIST.BILL_DT"), case="normal"),
  dict(name="연회비", domain="CARD",
       d="카드 상품의 연간 회비",
       real=dict(stored_as="CARD_PRDT_MST.ANNL_FEE"), case="normal"),

  # ===== DEPOSIT 보조 =====
  dict(name="입금", domain="DEPOSIT",
       d="수신 계좌로 자금이 들어오는 거래",
       real=dict(expressed_as=dict(column="DEP_TXN_HIST.TXN_TYPE_CD", value="D"),
                 dated_by="DEP_TXN_HIST.TXN_DT", attribute_of=["DEP_TXN_HIST.TXN_AMT"]), case="normal"),
  dict(name="출금", domain="DEPOSIT",
       d="수신 계좌에서 자금이 나가는 거래",
       real=dict(expressed_as=dict(column="DEP_TXN_HIST.TXN_TYPE_CD", value="W"),
                 dated_by="DEP_TXN_HIST.TXN_DT"), case="normal"),
  dict(name="정기예금", domain="DEPOSIT",
       d="약정 기간을 정해 예치하는 수신 상품",
       real=dict(expressed_as=dict(column="DEP_PRDT_MST.DEP_PRDT_TYPE_CD", value="20")), case="normal"),
  dict(name="적금", domain="DEPOSIT",
       d="일정액을 적립하는 수신 상품",
       real=dict(expressed_as=dict(column="DEP_PRDT_MST.DEP_PRDT_TYPE_CD", value="30")), case="normal"),
  dict(name="계좌개설", domain="DEPOSIT",
       d="수신 계좌가 개설된 사건", syn=["개설"],
       real=dict(dated_by="DEP_ACCT_MST.OPEN_DT"), case="normal"),
  dict(name="이자지급", domain="DEPOSIT",
       d="예금 이자가 고객에게 지급된 거래", syn=["예금이자"],
       real=dict(identified_by="DEP_INT_PAY_HIST.INT_PAY_NO", dated_by="DEP_INT_PAY_HIST.INT_PAY_DT",
                 attribute_of=["DEP_INT_PAY_HIST.INT_PAY_AMT"]), case="normal"),
  dict(name="해지환급금", domain="DEPOSIT",
       d="계좌 해지 시 고객에게 환급된 금액",
       real=dict(stored_as="DEP_ACCT_CLS_HIST.RFND_AMT"), case="normal"),

  # ===== RISK 보조 =====
  dict(name="신용평가", domain="RISK",
       d="고객의 신용 위험을 평가하는 행위와 그 결과 (등급·점수 포괄)",
       real=dict(identified_by="CRDT_EVAL_HIST.EVAL_NO", dated_by="CRDT_EVAL_HIST.EVAL_DT"),
       case="granularity"),
  dict(name="신용점수", domain="RISK",
       d="신용평가로 산정된 수치형 점수 (0~1000)",
       real=dict(stored_as="CRDT_EVAL_HIST.CRDT_SCR"), case="granularity"),
  dict(name="익스포저", domain="RISK",
       d="고객에 대한 월별 신용 익스포저 금액", syn=["신용익스포저"],
       real=dict(stored_as="RISK_EXPSR_INFO.EXPSR_AMT"), case="normal"),
  dict(name="충당금", domain="RISK",
       d="예상 손실에 대비해 적립하는 금액", syn=["대손충당금"],
       real=dict(stored_as="PROV_CALC_HIST.PROV_AMT",
                 attribute_of=["PROV_CALC_HIST.PROV_RATE"]), case="normal"),
  dict(name="이상거래", domain="RISK",
       d="부정 사용이 의심되어 탐지된 거래", syn=["FDS탐지", "사기의심거래"],
       real=dict(identified_by="FRAUD_DTCT_HIST.DTCT_NO", dated_by="FRAUD_DTCT_HIST.DTCT_DT",
                 segmented_by="FRAUD_DTCT_HIST.DTCT_TYPE_CD", measured_by="M_FRAUD_CONF_RATE"), cs="CS_FRAUD_TYPE", case="normal"),
  dict(name="보이스피싱", domain="RISK",
       d="보이스피싱 유형으로 탐지된 이상거래",
       real=dict(expressed_as=dict(column="FRAUD_DTCT_HIST.DTCT_TYPE_CD", value="03")), case="normal"),

  # ===== 의도된 결손 (Term 미등재 — 세계에만 존재) =====
  dict(name="중도상환수수료", domain="LOAN",
       d="중도상환 시 부과되는 수수료 (컬럼 LOAN_ERLY_RPYMT_HIST.ERLY_RPYMT_FEE 존재)",
       real=dict(stored_as="LOAN_ERLY_RPYMT_HIST.ERLY_RPYMT_FEE"),
       layer="EXCLUDED", case="boundary:no_term",
       expected="search_columns 폴백으로 접근 가능(컬럼 Description 존재) — 낮은 신뢰도 표명 필수"),
  dict(name="휴면계좌", domain="DEPOSIT",
       d="장기 미거래 계좌 — 세계에 분류 기준 자체가 미정의 (컬럼도 없음)",
       real=dict(),
       layer="EXCLUDED", case="boundary:no_term",
       expected="지어내지 않고 해당 개념이 레이어에 없음을 보고"),
]

# distractor Term — 레이어에 존재하나 물리 연결 없음(라이브러리 사실감 + 근접오답)
DISTRACTOR_TERMS = [
  ("연체이자",   "LOAN",    "연체 발생 시 부과되는 가산 이자"),
  ("가산금리",   "LOAN",    "기준금리에 더해지는 추가 금리"),
  ("우대금리",   "LOAN",    "조건 충족 시 차감되는 금리 혜택"),
  ("대환대출",   "LOAN",    "기존 대출을 상환하기 위해 새로 받는 대출"),
  ("거치기간",   "LOAN",    "원금 상환 없이 이자만 납부하는 기간"),
  ("분할상환",   "LOAN",    "원금을 여러 회차에 나누어 상환하는 방식"),
  ("근저당",     "LOAN",    "담보 부동산에 설정하는 저당권의 일종"),
  ("질권",       "LOAN",    "동산·권리를 담보로 잡는 권리"),
  ("채무조정",   "LOAN",    "상환 곤란 채무자의 채무 조건을 변경하는 절차"),
  ("부도",       "LOAN",    "채무 불이행이 확정된 상태"),
  ("신용공여",   "RISK",    "고객에게 제공된 신용의 총칭"),
  ("한도소진율", "RISK",    "부여된 한도 대비 사용 비율"),
  ("예대마진",   "RISK",    "대출 금리와 예금 금리의 차이"),
  ("카드론",     "CARD",    "카드 회원 대상 장기 대출 서비스"),
  ("현금서비스", "CARD",    "카드 회원 대상 단기 현금 대출"),
  ("선결제",     "CARD",    "청구일 이전에 미리 결제하는 행위"),
  ("포인트",     "CARD",    "카드 이용 실적에 따라 적립되는 포인트"),
  ("자동이체",   "DEPOSIT", "지정일에 자동으로 실행되는 이체"),
  ("예금자보호", "DEPOSIT", "예금보험공사가 보장하는 예금 보호 제도"),
  ("복리",       "DEPOSIT", "이자에 이자가 붙는 이자 계산 방식"),
  ("중도해지이율", "DEPOSIT", "만기 전 해지 시 적용되는 낮은 이율"),
]

# ============================================================
# 메트릭 — base_filters 가 '정본 정의식 vs 소박한 재계산'을 가르는 함정
# ============================================================
METRICS = [
  dict(id="M_LOAN_DLNQ_RATE", name="대출연체율", grain="LOAN_ACCT_MST(계좌)",
       expr="COUNT(CASE WHEN DLNQ_FLG='Y' THEN 1 END)*1.0/COUNT(*)",
       base_filters=["ACCT_STAT_CD NOT IN ('04','05')"],
       sql="SELECT ROUND(COUNT(CASE WHEN DLNQ_FLG='Y' THEN 1 END)*1.0/COUNT(*),4) FROM LOAN_ACCT_MST WHERE ACCT_STAT_CD NOT IN ('04','05')",
       note="분모에서 상각·완제 제외 — 정본 필터"),
  dict(id="M_CARD_DLNQ_RATE", name="카드연체율", grain="CARD_BILL_HIST(청구월)",
       expr="COUNT(CASE WHEN DLNQ_FLG='Y' THEN 1 END)*1.0/COUNT(*)", base_filters=[],
       sql="SELECT ROUND(COUNT(CASE WHEN DLNQ_FLG='Y' THEN 1 END)*1.0/COUNT(*),4) FROM CARD_BILL_HIST"),
  dict(id="M_TOTAL_LOAN_BAL", name="대출잔액총계", grain="LOAN_ACCT_MST",
       expr="SUM(LOAN_BAL_AMT)", base_filters=["ACCT_STAT_CD <> '05'"],
       sql="SELECT SUM(LOAN_BAL_AMT) FROM LOAN_ACCT_MST WHERE ACCT_STAT_CD <> '05'"),
  dict(id="M_AVG_INT_RATE", name="평균금리", grain="LOAN_ACCT_MST",
       expr="AVG(INT_RATE)", base_filters=["ACCT_STAT_CD NOT IN ('04','05')"],
       sql="SELECT ROUND(AVG(INT_RATE),3) FROM LOAN_ACCT_MST WHERE ACCT_STAT_CD NOT IN ('04','05')",
       note="활성 계좌 기준 — 상각·완제 제외"),
  dict(id="M_APRV_RATE", name="승인율", grain="LOAN_APPL_HIST",
       expr="COUNT(APPL_STAT_CD='03')*1.0/COUNT(APPL_STAT_CD IN ('03','04'))", base_filters=[],
       sql="SELECT ROUND(COUNT(CASE WHEN APPL_STAT_CD='03' THEN 1 END)*1.0/COUNT(CASE WHEN APPL_STAT_CD IN ('03','04') THEN 1 END),4) FROM LOAN_APPL_HIST",
       note="분모가 '심사 완료 건(승인+거절)' — 접수·심사중·취소 제외가 함정"),
  dict(id="M_BNS_CNSNT_RATE", name="방카슈랑스동의율", grain="LOAN_APPL_HIST",
       expr="COUNT(BNS_CD='Y')*1.0/COUNT(BNS_CD<>'X')", base_filters=[],
       sql="SELECT ROUND(COUNT(CASE WHEN BNS_CD='Y' THEN 1 END)*1.0/COUNT(CASE WHEN BNS_CD<>'X' THEN 1 END),4) FROM LOAN_APPL_HIST",
       note="분모에서 X(해당없음) 제외 — 기존 픽스처 계승 함정"),
  dict(id="M_ERLY_RPYMT_RATE", name="중도상환율", grain="LOAN_ACCT_MST",
       expr="COUNT(DISTINCT 중도상환 계좌)*1.0/COUNT(전체 실행 계좌)", base_filters=[],
       sql="SELECT ROUND((SELECT COUNT(DISTINCT LOAN_ACCT_NO) FROM LOAN_ERLY_RPYMT_HIST)*1.0/(SELECT COUNT(*) FROM LOAN_ACCT_MST),4)"),
  dict(id="M_REVOLVING_RATE", name="리볼빙이용률", grain="CARD_BILL_HIST",
       expr="COUNT(RPYMT_MTHD_CD='3')*1.0/COUNT(*)", base_filters=[],
       sql="SELECT ROUND(COUNT(CASE WHEN RPYMT_MTHD_CD='3' THEN 1 END)*1.0/COUNT(*),4) FROM CARD_BILL_HIST"),
  dict(id="M_FRAUD_CONF_RATE", name="이상거래확정률", grain="FRAUD_DTCT_HIST",
       expr="COUNT(PROC_STAT_CD='03')*1.0/COUNT(*)", base_filters=[],
       sql="SELECT ROUND(COUNT(CASE WHEN PROC_STAT_CD='03' THEN 1 END)*1.0/COUNT(*),4) FROM FRAUD_DTCT_HIST"),
  dict(id="M_DEP_AVG_BAL", name="평균예금잔액", grain="DEP_ACCT_MST",
       expr="AVG(ACCT_BAL_AMT)", base_filters=["ACCT_STAT_CD <> '40'"],
       sql="SELECT ROUND(AVG(ACCT_BAL_AMT),0) FROM DEP_ACCT_MST WHERE ACCT_STAT_CD <> '40'",
       note="해지 계좌 제외"),
  dict(id="M_MKT_CNSNT_RATE", name="마케팅수신동의율", grain="CUST_CNSNT_INFO",
       expr="COUNT(CNSNT_YN='Y')*1.0/COUNT(*) WHERE 항목=마케팅수신", base_filters=["CNSNT_ITEM_CD='01'"],
       sql="SELECT ROUND(COUNT(CASE WHEN CNSNT_YN='Y' THEN 1 END)*1.0/COUNT(*),4) FROM CUST_CNSNT_INFO WHERE CNSNT_ITEM_CD='01'"),
]

# ---- 접미사 기반 auto desc (저작 desc 없는 배경 컬럼용) ----
SUFFIX_DESC = [
    ("CREATED_AT", "레코드 생성 시각."), ("UPDATED_BY", "레코드를 최종 수정한 사용자 ID."),
    ("_NO", "식별 번호."), ("_DT", "일자."), ("_YM", "기준 연월(YYYYMM)."),
    ("_AMT", "금액(원)."), ("_RATE", "비율(%)."), ("_CD", "코드."),
    ("_YN", "여부(Y/N)."), ("_FLG", "여부 플래그."), ("_NM", "명칭."),
]
def auto_desc(table, col):
    for suf, d in SUFFIX_DESC:
        if col.endswith(suf) or col == suf:
            return f"{TABLES[table]['grain']} 레코드의 {col} — {d}"
    return f"{TABLES[table]['grain']} 레코드의 {col} 항목."
